#!/bin/bash
# In this file, you can override functions included with ci-studio-common to meet your needs.
# Please consider contributing any enhancements or improvements to chef/ci-studio-common

document "wait_or_fail_for_svc_to_load" <<DOC
  Helper function to wait for a Habitat service (hab svc) to be loaded by the Habitat Supervisor.

  @(arg:1) PKG_IDENT A Habitat package identifier (ex: core/redis)
  @(arg:2) Number of seconds to wait before returning 1. (default: 60 seconds)
  @(arg:3) Wheter or not this process runs silently
DOC
function wait_or_fail_for_svc_to_load() {
  local SECONDS_WAITING=${2:-60}
  local COUNTER=0

  while [[ $(hab sup status "$1" | tail -1 | awk '{print $3}') != "up" ]]; do
    sleep 1

    if [[ $COUNTER -ge "$SECONDS_WAITING" ]]; then
      echo " => Habitat service '$1' failed to load."
      return 1
    fi

    (( COUNTER=COUNTER+1 ))

    [[ "${3:-}" != "silent" ]] && echo " => Waiting to load svc '$1'. ($COUNTER of $SECONDS_WAITING)";
  done
}

document "svc_running" <<DOC
  Helper function to ask the Habitat supervisor if a service is running or not.

  @(arg:1) PKG_IDENT A Habitat package identifier (ex: core/redis)
DOC
function svc_running() {
  local rc=0
  local svc_status=""
  svc_status=$(hab svc status "$1" 2>/dev/null)
  rc=$?
  if [[ $rc != 0 ]]; then
    return $rc
  fi

  if [[ $(echo "$svc_status" | tail -1 | awk '{print $3}') == "up" ]]; then
    return 0
  else
    return 1
  fi
}
